### ISSUE TITLE
6.99.12.3 Checklist

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1124]
- [x] Fix Editra spellcheck.
- [x] Fix id issue from talk video.
- [x] Allow displayables to expose and apply properties themselves.
