### ISSUE TITLE
6.99.12.4 TODO List

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1136]
- [x] #1132 AFM not working.
- [x] #1135 Drawing canvas 
- [x] #1129 Audio does not loop during the fadeout period.
- [x] #1126 Console improvements (some of them).
- [x] Disable AFM if when self-voicing is enabled.
- [x] Viewport scrollbars and style should inherit the style prefix.
- [x] #1139 Save/load screen retention glitch
