### ISSUE TITLE
6.99.13 Prerelease TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1231]
- [x] Allow Say to take arguments.
- [x] Global say argument callback.
- [x] Provide a way for character to not allow clicking. (To allow hyperlinked dialogue.)

- [x] #1228 _history_list.voice.filename will be None if Voice Sustain is on
- [x] #1225 show at nullifies transition.
- [x] #1214 Inconsistent newline style.
- [x] #1204 Better error message (done, needs to be closed at prerelease)
- [x] #1181 ATL transform bug relating to "on show" and "on hide"
- [x] #1174 Blocking when sound plays. (Can't repeat.)
- [x] #1171 Answer question.
- [x]  #1113 Scaling window make text in Help goes out-of-frame (new GUI)

- [x] screen game_menu should take yinitial as an argument.
- [x] Really tiny launcher errors.
- [x] Changelog say-with-attributes.
- [x] Ensure itch/butler work well.
- [x] https://lemmasoft.renai.us/forums/ucp.php?i=pm&mode=view&f=0&p=260161
- [x]  pop_nvl_list fires when rolling back, so entries get missing or it crashes when rolling back to the start of a page
- [ ] Sound volume issue.
- [x] Navigate script button gives an error.
- [x] show layer at resetting?

**Comment by pratomoastan** [comment]
hi tom i want to navigate the launcher script via "Navigate Script"​ to
look for new #TODO Tag , but i cant beacuse theres was something that i
cant read because the font was so small , so i dont know what is that .
#6.99.13.2685.
