### ISSUE TITLE
6.99.14 TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1300]
Stuff that's not in other issues, so I don't forget.

- [x] Compat config.zap_transient.
- [x] Document slow_abortable.
- [x] Optional framerate lock.
- [x] New tooltips.
- [x] Custom statements should be able to return their own label.
- [x] gui.text_properties should not set xalign and xpos at the same time. (Make use of this in the gui.)
- [x] Run expensive prediction of there's time in a frame and no events are pending.
- [x] Document config.cache_surfaces and NPOT.
- [x] Store updates may not be computed correctly. (It seems like modules are leaking into the store that's being saved.)
- [x] Document the layer property of a screen.

**Comment by XavierDD1st** [comment]
What about a git source uploader?
