### ISSUE TITLE
6.99.14.1 TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1355]
- [x] The image load log can jump around in size and move offscreen.
- [x] We can save image cache by making _transparent_tile a Frame rather than an im.Tile.
- [x] Include the date and time in traceback.txt and errors.txt.
- [x] https://lemmasoft.renai.us/forums/viewtopic.php?p=475202#p475202
- [x] Maintain gpu and memory texture cache sizes.
- [x] Proactively make_ready 1 texture per frame.
