### ISSUE TITLE
CDS TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#1844]
- [x] Ren'Py advances after parsing a Ren'Py statement, meaning that we miss statements.
- [x] Erroneous statements may not be caught.
- [x] Make sure we can predict labels and SubParses in addition to displayables (predict_next)
