### ISSUE TITLE
7.4 Release Checklist

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2498]
- [x] Audit controller support, to see if the issue with Steam and controllers is repeatable, and to see if modal screens and controllers/keyboards cause problem. Potentially generate repeat button presses when a controller button is held down.
- [x] Audit font support, per https://lemmasoft.renai.us/forums/viewtopic.php?p=535896#p535896
- [x] Work to improve startup time on windows, perhaps by deferring calls to reg to a background thread. Also make sure that recompilation doesn't occur on initial start.

**Comment by renpytom** [comment]
#3 wasn't done, as profiling showed it only slowed start by < 10ms.
