### ISSUE TITLE
GL TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#2710]
- [x] Avoid loading the ANGLE dll. (SDL can find it.)
- [x] config.log_gl_extensions
- [x] config.log_gl_shaders
