### ISSUE TITLE
Renpy calls and ATL roadmap

### ISSUE THREAD

**Issue by Gouvernathor** [renpy/renpy#5102]
When an ATL transform is called, three things happen : the inner scope is updated (as with any call in renpy ot python), the parameters are curryfied and prepared for a potential next call, and the child of the transform is updated. All three of these are buggy.
Some parameters are not managed and treated as they should : pos-only are treated as pos-or-kw, required kw-only are not handled and cause exceptions, and variadic parameters are rejected at parse time. This affects the inner scope update and the correct currying of parameters for the next call.
The rules for setting the child are not consistent, resulting in the very function made to do it (At) failing in some edge cases, not to mention when you call the transform directly (not everyone uses At).

- [ ] Reform the ParameterInfo class into one with or around inspect.Signature interface. This is necessary to settle the following evolutions on solid ground.
- [ ] Fix ATL calls and currying, which comes into subtasks.
  - [ ] Fix and enable non-classic parameters (which means rewriting that part of the code)
    - [ ] Fix positional-only parameters to be just that (instead of treating them as pos-or-kw)
    - [ ] Fix/Enable keyword-only required parameters
    - [ ] Enable var-pos and var-kw parameters (\*args and \*\*kwargs)
    - [ ] Fix the "long-time nonsense" call of ParameterInfo, which yield inconsistent ParameterInfo objects
  - [ ] Clarify and improve how the ATL child is managed
    - [ ] Fix `At` not setting the child sometimes
    - [ ] clarify when the child is set depending on the signature (the child parameter, the old_widget parameter, and the case with no positional parameter)
- [ ] Allow the child to be accessed by the `child` local variable in ATL, regardless of the signature (a pure improvement, but it will help if taken into account in the previous steps)

As a sidenote, a difficulty when currying ATL is that in the resulting signature, the default values of the passed parameters are actual, evaluated values, whereas a "raw" ATL transform has evaluable expressions as default values of the optional parameters. Properly managing that will probably require two Signature classes, or two Parameter classes, or both.

**Comment by renpytom** [comment]
@Gouvernathor Can you taker your new pull requests out of draft status, so I can merge them? (Also, a short description other than the title would help.)

**Comment by Gouvernathor** [comment]
They are not tested and need to be, I will do it eventually.
