### ISSUE TITLE
TODO list for text oversampling

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#707]
- [x] sfonts need to be supplied the original size and scaled up. (This needs to be done precisely - perhaps store the original and scaled sizes.)
- [x] embedded displayables need to be scaled up.
- [x] outlines must be placed correctly.
- [x] text tag parameters may need to be scaled.
- [x] add a switch to turn off. (And an environment variable to control that switch.)
