### ISSUE TITLE
Interface 7 TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#871]
- [x] Help screen.
- [x] Indicate newest save slot.
- [x] Rewrite gui.rpy to take advantage of the fixed in the game_menu screen.
- [x] Ensure buttons and bars have an insensitive state.
- [x] Viewport Grid (partially-rendering viewport).
- [x] Improved RevertableList rollback.
- [x] NVL-mode screens.
- [x] Vbar images.
- [x] Button images.
- [x] New preferences design.
- [x] Fix yesno, about, and help style names.
- [x] Rename "screen yesno_prompt" to "screen confirm"
- [x] Rename "file_picker" to "file_slots".
- [x] Skip mode indicator.
- [x] Notification screen.
- [x] History screen.
- [x] Document HistoryEntry, _history, and _history_list.
- [x] Main Menu / Game Menu images.
- [x] NVLEntry.
- [x] ChoiceEntry Objects
- [x] Increase button padding.
- [x] Tablet gui - preferences.
- [x] 1-base save slots. (Start with 1, rather than 0.)
- [x] Expose quick/auto saves on slots.
- [x] Audit all style names.
- [x] Phone gui - not sure.
- [x] CTC indicator? At least better support for one. CTC screen?
