### ISSUE TITLE
New Translate Order / Deferred Translate todo.

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#899]
- [x] Compat.
- [x] Restore the gui namespace before running translate code.
- [x] Ensure that launcher style backups are made by renpy.config.change_language_callbacks.
- [x] Ensure that deferred styles do not break error handling.
