### ISSUE TITLE
Options.rpy TODO

### ISSUE THREAD

**Issue by renpytom** [renpy/renpy#925]
- [x] A config value should control the default for window show / window hide / auto.
- [x] Support define config.savedir = 'foo-1' properly.
- [x] Support default preference.whatever = 42 properly.
- [x] Add config.window_icon.
